### ISSUE TITLE
Case Sensitive has the opposite effect

### ISSUE THREAD

**Issue by Aida-Enna** [jojos38/Word-Notification-Improved#1]
With "Case Sensitive" turned off, the plugin will only trigger if the proper casing is used. If it's turned on, any CaSiNg will work. It's having the opposite effect. I tried modifying the plugin to swap it but the changes I made to the plugin don't seem to be taking effect? I've never messed with plugins much before so I'm making it an issue instead of a PR to fix it. Sorry!

For example, if I added the word "aida" to the filter - With Case Sensitive turned off, it would only respond to "aida" and not "Aida" or "AIDA" or any casing variation. Turning Case Sensitive on makes it recognize these.

Nice work on the plugin - I was looking for a more updated version of the Word Notification plugin and I'm happy with what I found. 👍

**Comment by jojos38** [comment]
I will make some test and see what I can do, thanks for the report

**Comment by jojos38** [comment]
I fixed the issue, it was simply this line
const content = settings["case-sensitive"] ? message.content: message.content.toLowerCase();
I had inverted the two fields around the ":"
