### ISSUE TITLE
Plugin not working post discord update at the end of September

### ISSUE THREAD

**Issue by Aida-Enna** [jojos38/Word-Notification-Improved#11]
There was a big discord update at the end of September and it broke a lot (all?) plugins. Since then, things have somewhat stabalized, but this plugin still isn't working. It's the last one I need to have my full experience back (I moderate a lot of servers and this helped *immensely*), and was hoping it could be fixed if possible. Thank you!

**Comment by jojos38** [comment]
Hey, you can try the new version it should work
Thanks for using my plugin

**Comment by Aida-Enna** [comment]
Yup, that fixed it! Thank you very much for your hard work! 👍

**Comment by jojos38** [comment]
> Yup, that fixed it! Thank you very much for your hard work! 👍

I forgot to mention that you cannot click notifications to go to the message anymore, I didn't find a fix for that (although it wasn't working properly before anyway)
