### ISSUE TITLE
Plugin stopped working

### ISSUE THREAD

**Issue by BloodWorkVR** [jojos38/Word-Notification-Improved#15]
Keeps saying cant be started since the last Discord updates.

**Comment by jojos38** [comment]
Hey I'm sorry I'm quite busy these days I'll try to do it when I get some time, or if anyone else feel like doing a pull request until then it would be awesome

**Comment by Aida-Enna** [comment]
Sorry, been bedridden for a few days - Just updated and saw the issue and fixed it. 👍

**Comment by jojos38** [comment]
Thanks to Aida-Enna the issue is solved, have a nice day
