### ISSUE TITLE
Mayus problem

### ISSUE THREAD

**Issue by dav1312** [jojos38/Word-Notification-Improved#3]
Word to check: HELLO
Case sensitive: enabled
The word "hello" triggers the alert, the word "HELLO" doesn't

Word to check: HELLO
Case sensitive: disabled
Neither "HELLO" nor "hello" trigger the alert 

Word to check: Hello
Case sensitive: enabled
The word "hello" triggers the alert, the word "HELLO" doesn't

**Comment by jojos38** [comment]
I fixed the issue, thanks for the report!
