### ISSUE TITLE
[IMPROVEMENT] Change BDFDB toast style

### ISSUE THREAD

**Issue by dav1312** [jojos38/Word-Notification-Improved#5]
![image](https://user-images.githubusercontent.com/63931154/115393956-8f130000-a1e2-11eb-9c2b-1e43967a6fe6.png)

```js
var toastString = guild.name + "\n\# " + channel.name + "\n\n" + author.username + ": " + notifWord;
```
```js
var toastString = "DM\n\n" + author.username + ": " + message.content;
```
Credits to [qwert](https://github.com/QWERTxD) for making this part ↓
```js
// Should we send a bdapi notification?
if (settings["bdapi-notification"]) {
	const timeout = settings["bdapi-display-time"];
	BdApi.showToast(toastString, {type: "info"});
}
// Should we send a bdfdb notification?
if (settings["bdfdb-notification"]) {
	const timeout = settings["bdfdb-display-time"];
	const toast = BDFDB.NotificationUtils.toast(toastString, {
		timeout: timeout*1000,
		barColor: BDFDB.UserUtils.getStatusColor("online", true),
		avatar: BDFDB.UserUtils.getAvatar(author.id)
	});
	toast.addEventListener("click", _ => { this.goToMessage(guildID, channel.id, message.id); });
}
```

**Comment by jojos38** [comment]
This is a great idea! Thank you
Why removing the timeout from BdApi toast though?

**Comment by jojos38** [comment]
This is a great idea! Thank you
Why removing the timeout from BdApi toad though?

**Comment by jojos38** [comment]
Although I like the idea, I didn't want to change the toast for everyone since some users could prefer the old one. Therefor I added the ability to edit the notification message for Windows and for Toasts under Advanced Settings
I added the avatar and barColor from your code, thanks!
