### ISSUE TITLE
Notifications aren't working

### ISSUE THREAD

**Issue by Aida-Enna** [jojos38/Word-Notification-Improved#8]
Heya! I recently upgraded to Windows 11 and was getting notifications fine, but after a recent update BDFDB, the notifications from this plugin aren't working anymore. I'm fairly certain that's when it broke, but it might have been a couple days (I thought my life was finally drama free until I realized!).

The reason I'm posting here and not the BDFDB page is because notifications are working for that plugin - If I click settings on BDFDB and then check for updates, it shows a working toast notification:
![image](https://user-images.githubusercontent.com/5483362/139577184-895a716e-e646-490c-8b01-a8b543c3cb1b.png)

However, putting both the BDAPI and the Windows notification code on the MessageReceived handler does nothing and the plugin doesn't work. I'm not familiar enough with how BD does it's internals to diagnose it :c

**Comment by jojos38** [comment]
Hey! Thank you for your report, I will take a look at it asap and tell you what I can do
I didn't even notice it

**Comment by jojos38** [comment]
Hey, I just want to add that I'm very busy these days I really don't know how much time it's gonna take, I recommend you use bdapi notifications meanwhile

**Comment by Aida-Enna** [comment]
I understand that - Unfortunately, the BDAPI Notifications aren't working either. I've seen some very strange behavior - I put a test message in the beginning of messagereceived (as mentioned before) and it didn't work, but when I clean reinstalled BD on discord PTB, it spammed me with test messages via the BDAPI 6 times and then went silent again and refused to show anymore.

I'm not sure what is going on here, lol.

**Comment by jojos38** [comment]
I decided to just take a glance at it and ended up fixing it, here you are!
Thanks for reporting the bug
